name: CI
on:
    push:
        branches-ignore:
            - main
jobs:
    Lint:
        runs-on: ubuntu-latest
        timeout-minutes: 5
        strategy:
            matrix:
                node: ['14', '16']
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node }}
                  cache: npm
            - run: 'npm i && npm run lint'
    Check:
        runs-on: ubuntu-latest
        timeout-minutes: 5
        strategy:
            matrix:
                node: ['14', '16']
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node }}
                  cache: npm
            - run: 'npm i && npm run check'
